### ISSUE TITLE
JTReg failure: jdk/internal/jrtfs/Basic.java

### ISSUE THREAD

**Issue by pushkarnk** [canonical/openjdk-21-crac#3]
This looks like a crac-related failure. JTR attached.

```
Caused by: java.lang.IllegalAccessException: class jdk.internal.jimage.BasicImageReader cannot access class jdk.internal.crac.Core$Priority (in module java.base) because module java.base does not export jdk.internal.crac to unnamed module @1fef4e41
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
	at jdk.internal.jimage.BasicImageReader.registerIfCRaCPresent(BasicImageReader.java:181)
```
[Basic.jtr.txt](https://github.com/user-attachments/files/16189061/Basic.jtr.txt)

**Comment by pushkarnk** [comment]
Yes, `--add-exports=java.base/jdk.internal.crac=ALL-UNNAMED --add-exports=java.base/jdk.crac.impl=ALL-UNNAMED` should fix the test failure.

But it looks like this is a general problem with `jdk.internal.jimage.BasicImageReader`, if the latter gets invoked through reflection.

This is the full exception message and the stack from the test method (Basic.java):
```
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalAccessException: class jdk.internal.jimage.BasicImageReader cannot access class jdk.internal.crac.Core$Priority (in module java.base) because module java.base does not export jdk.internal.crac to unnamed module @5b6f7412
	at jdk.internal.jimage.BasicImageReader.registerIfCRaCPresent(BasicImageReader.java:206)
	at jdk.internal.jimage.BasicImageReader.<init>(BasicImageReader.java:110)
	at jdk.internal.jimage.ImageReader$SharedImageReader.<init>(ImageReader.java:229)
	at jdk.internal.jimage.ImageReader$SharedImageReader.open(ImageReader.java:243)
	at jdk.internal.jimage.ImageReader.open(ImageReader.java:67)
	at jdk.internal.jimage.ImageReader.open(ImageReader.java:71)
	at jdk.internal.jrtfs.SystemImage.open(SystemImage.java:60)
	at jdk.internal.jrtfs.JrtFileSystem.<init>(JrtFileSystem.java:90)
	at jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:109) ****
	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:128)
	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:107)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at Test.main(Test.java:12)
Caused by: java.lang.IllegalAccessException: class jdk.internal.jimage.BasicImageReader cannot access class jdk.internal.crac.Core$Priority (in module java.base) because module java.base does not export jdk.internal.crac to unnamed module @5b6f7412
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
	at jdk.internal.jimage.BasicImageReader.registerIfCRaCPresent(BasicImageReader.java:181)
	... 13 more

```

I am curious about why `jdk.internal.jimage.BasicImageReader` is attributed to an "unnamed module" here, while it belongs to `java.base`. Possibly, that's because it is a part of a call-sequence invoked via reflection. Also, notice that starting `****`, the frames are not annotated with `java.base` as the module. There's something from a modularity PoV that I am missing here. 

We might have to find a more general solution to this problem, in the longer term.

**Comment by pushkarnk** [comment]
Oh, btw I am using this isolated reproducer:

```
import java.util.HashMap;
import java.util.Map;
import java.nio.file.FileSystems;
import java.io.IOException;
import java.net.URI;

public class Test {
    public static void main(String[] args) throws Exception {
        Map<String, String> env = new HashMap<>(); 
        env.put("java.home", System.getProperty("java.home"));
        try {
            FileSystems.newFileSystem(URI.create("jrt:/"), env);
        } catch (IOException ioExp) {
            throw new RuntimeException(ioExp);
        }
    }
}
```

**Comment by pushkarnk** [comment]
[This](https://github.com/openjdk/crac/commit/82dd03e89ba08af8039ef7854e9d349e77415d8c#diff-7b8e1a1d78395e278c6ddb7da29ff18fcc8b6ecb624bfaf77f95dd009b2988a4) fixes the problem upstream.
